name: Prerelease Binary

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[a-z0-9]+"
jobs:
  goreleaser:
    if: github.repository == 'gobackup/gobackup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "Build Web"
        run: |
          cd web
          yarn && yarn build
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: olegtarasov/get-tag@v2.1
        id: tagName

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.tagName.outputs.tag }}
          tags: |
            huacnlee/gobackup:${{ steps.tagName.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
